export default [
  {
    "login": "adityakumarsinha03",
    "id": 54764964,
    "node_id": "MDQ6VXNlcjU0NzY0OTY0",
    "avatar_url": "https://avatars.githubusercontent.com/u/54764964?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/adityakumarsinha03",
    "html_url": "https://github.com/adityakumarsinha03",
    "followers_url": "https://api.github.com/users/adityakumarsinha03/followers",
    "following_url": "https://api.github.com/users/adityakumarsinha03/following{/other_user}",
    "gists_url": "https://api.github.com/users/adityakumarsinha03/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/adityakumarsinha03/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/adityakumarsinha03/subscriptions",
    "organizations_url": "https://api.github.com/users/adityakumarsinha03/orgs",
    "repos_url": "https://api.github.com/users/adityakumarsinha03/repos",
    "events_url": "https://api.github.com/users/adityakumarsinha03/events{/privacy}",
    "received_events_url": "https://api.github.com/users/adityakumarsinha03/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "imanshu11",
    "id": 69692304,
    "node_id": "MDQ6VXNlcjY5NjkyMzA0",
    "avatar_url": "https://avatars.githubusercontent.com/u/69692304?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/imanshu11",
    "html_url": "https://github.com/imanshu11",
    "followers_url": "https://api.github.com/users/imanshu11/followers",
    "following_url": "https://api.github.com/users/imanshu11/following{/other_user}",
    "gists_url": "https://api.github.com/users/imanshu11/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/imanshu11/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/imanshu11/subscriptions",
    "organizations_url": "https://api.github.com/users/imanshu11/orgs",
    "repos_url": "https://api.github.com/users/imanshu11/repos",
    "events_url": "https://api.github.com/users/imanshu11/events{/privacy}",
    "received_events_url": "https://api.github.com/users/imanshu11/received_events",
    "type": "User",
    "site_admin": false
  }
  ];